apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kan-brewer.fullname" . }}
  labels:
    {{- include "kan-brewer.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - cr.kanister.io
    resources:
      - actionsets
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
      - persistentvolumeclaims
    verbs:
      - get
      - list
