name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  HELM_REPO: haimgel/helm-charts

jobs:
  release-helm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # # To be able to get OIDC ID token to sign images.
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v5

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: azure/setup-helm@v3

      - name: Release helm chart
        env:
          VERSION: ${{ steps.meta.outputs.version }}
        run: |
          cd helm
          helm package kan-brewer --version $VERSION --app-version $VERSION
          helm push kan-brewer-$VERSION.tgz oci://$REGISTRY/$HELM_REPO
