name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  HELM_REPO: haimgel/helm-charts

jobs:
  release-helm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # # To be able to get OIDC ID token to sign images.
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v5

      - uses: azure/setup-helm@v3

      - name: Release helm chart
        env:
          VERSION: ${{ steps.meta.outputs.major }}.${{ steps.meta.outputs.minor }}.${{ steps.meta.outputs.patch }}
        run: |
          cd helm
          helm package kan-brewer --version $VERSION --app-version $VERSION
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} --username ${{ github.repository_owner }} --password-stdin
          helm push --debug kan-brewer-$VERSION.tgz oci://${{ env.REGISTRY }}/${{ env.HELM_REPO }}
